### ISSUE TITLE
VnV Plan Review: General Information Section

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#28]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The paragraph starting with "This document..." should be under the General Information heading.
- [x] "ImgBeamer" by itself (as opposed to "the ImgBeamer software" or "the ImgBeamer program") shouldn't have "the" before it.
- [x] The phrase "scanning electron microscope image formation" in parentheses seems like it is a definition of ImgBeamer, but it doesn't look like a definition to me.
- [x] Referring to the "Software Requirements Specification (SRS) document" is redundant - you don't need to say "document".
- [x] Since testing hasn't occurred yet, it should say "Testing of ... its components **will be** conducted...."
- [x] "Ultimately" should have commas around it (i.e., "...and, ultimately, whether...").
- [x] It should be "...whether it meets **the requirements from** the SRS."

**Comment by joedf** [comment]
1. Yeah, I thought so too! Was confused, because the template had it before... ¯\_(ツ)_/¯

**Comment by joedf** [comment]
Thanks!
