### ISSUE TITLE
VnV Plan Review: Minor grammar issues in plan subsections

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#33]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

## SRS Verification Plan
- [x] I would say that "The SRS document **will be** reviewed..." since this document is the plan for your verification, assuming that it hasn't happened already.
- [x] Remove the first "or" in this sentence: "Most of the feedback has been provided as issues on GitHub, ~~or~~ as annotated documents, or by verbal exchange."
- [x] This sentence should be rewritten: "The author is then expected make the resolve the issues and makes accordingly throughout the development of the project."
- [x] In the last sentence, there is only one objective listed, so it should be "The key objective is to...."
   - [x] On my first read, it seemed like "sound" was going to be a verb until I got past it. While the above fix would help, I would also switch the order of "sound" and "coherent" to help mitigate this.

## Design Verification Plan
- [x] It should be "Decision**s** are made...."
   - [x] If these decisions were part of the conceptualization process, then it should be past tense for consistency (i.e., "Decision**s were** made...).
- [x] There shouldn't be spaces in "MG/MIS".
   - [x] I would put the references beside the document names themselves to be 100% clear (i.e., "MG [1]/MIS [2]").
- [x] There should be commas in this sentence: "The VnV team, as well as any volunteer**s** ~~users~~, are welcome to...."

## Implementation Verification Plan
- [x] I would get rid of the "any"s in the second sentence.
- [x] References to sections should be capitalized (e.g., "Section 4.6.")

## Automated Testing and Verification Tools
- [x] As a verb, "[unit test](https://en.wiktionary.org/wiki/unit_test)" doesn't have a hyphen.

**Comment by joedf** [comment]
Thanks, very helpful! Sorry for the pain if I caused any ahah

... Dyslexic 😬

**Comment by samm82** [comment]
No worries! I'm a detailed-oriented perfectionist, so I've always enjoyed proofreading lol
