### ISSUE TITLE
VnV Plan Review: Minor grammar issues in System Test Description section and subsections

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#34]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] In the intro, it should be "...the system tests that will be conducted **are** described...."

## Image Import and Export
- [x] The bulleted list of file types should be explained/introduced in the text.
- [x] For the Initial State of your tests, I would be more specific: "**ImgBeamer** loaded and idle."
- [x] For the Test Case Derivation of T1, it should be "These~~s~~ are some...."
- [x] Make sure you do quotation marks properly in LaTeX: ``` ``text'' ```.

## Spot Profile and Imaging Parameters
- [x] There should be a comma after "which".
- [x] "To satisfy R4..." should only have the "T" capitalized.
- [x] What is the difference between "loaded and idle" and "running and idle"? You should pick one for consistency.
- [x] In the Input of T3, "height" shouldn't be capitalized.
- [x] What does relative mean here? Is it a typo? "Width and Height as positive real numbers relative."
- [x] There are grammar issues in the Output of T3: "The spot layout should reflect these changes **and** display an updated arrangement with the given shape. The resulting image should exhibit expected effects as document**ed by** the SRS figures [4]."
   - Make sure to update this in all relevant spots!

## Image Quality Metric
- [x] It should be "To satisfy R7, the user **should** be able...."
- [x] There shouldn't be a comma after "truth".
- [x] The Output for T9 should be "A **number** that is...."
