### ISSUE TITLE
VnV Plan Review: Minor grammar issues in Tests for Nonfunctional Requirements section

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#35]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*
 
- [x] It should be "The follow**ing** tests...."
- [x] There should be commas here: "...the nonfunctional requirements, as defined in the SRS [4], are met."
- [x] There is an extra space where a comma should be in the third sentence (after "ImgBeamer").
- [x] For consistency, "portability" shouldn't be capitalized.
